### ISSUE TITLE
Please use force_install_dir before logon

### ISSUE THREAD

**Issue by solarsparq** [Gelmo/warfork-docker#1]
Good morning,

This appears to be a very common bug that started a few years ago.. order of command-line parameters with force_install_dir.  It must go before the logon parameter.  As a result, your Docker container is broken.  Thank you for creating this.  Hope you are able to resolve.  Here is the docker log output.

> Installing server ...

+ shopt -s extglob

+ SERVER_INSTALLED_LOCK_FILE=/home/warfork/server/installed.lock

+ WF_CUSTOM_CONFIGS_DIR=/var/wf

+ '[' -f /home/warfork/server/installed.lock ']'

+ installServer

+ echo '> Installing server ...'

+ /home/warfork/Steam/steamcmd.sh +login anonymous +force_install_dir /home/warfork/server +app_update 1136510 validate +quit

WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.

Redirecting stderr to '/home/warfork/Steam/logs/stderr.txt'

[  0%] Checking for available updates...

[----] Verifying installation...

Steam Console Client (c) Valve Corporation - version 1666144101

-- type 'quit' to exit --

Loading Steam API...OK

Connecting anonymously to Steam Public...OK

Waiting for client config...OK

Waiting for user info...OK

Please use force_install_dir before logon!

 Update state (0x41) staging, progress: 100.00 (740027080 / 740027080)

 Update state (0x81) verifying update, progress: 88.30 (653453355 / 740027080)

Error! App '1136510' state is 0x602 after update job.

**Comment by Gelmo** [comment]
Hey, sorry for the late response! Thank you for mentioning this. This was corrected in a commit I made a couple months ago: https://github.com/Gelmo/warfork-docker/commit/d3077132c811ffb23470234214596977d16b7e9d
